#!/usr/bin/env python3
"""
generate_fold_table.py

Reads Unicode's CaseFolding.txt and emits the Swift source file that defines
the simple (1:1) case-folding mapping table used by the SwiftFMDB LIKE
matcher (`Sources/FMUnicode/UnicodeLike.swift`).

We emit only the C (common) and S (simple) status entries, which together
form the simple case-folding mapping documented in CaseFolding.txt:

    A. To do a simple case folding, use the mappings with status C + S.

This is the same set ICU exposes through u_foldCase() with default flags,
which is what SQLite's ICU LIKE extension uses. The mapping is 1:1 by
construction, so callers can fold per code point without worrying about
length changes or 1:N expansion.

By default the script downloads the latest CaseFolding.txt from
unicode.org into a temporary file that is deleted as soon as parsing
finishes. Pass --input to use a pre-downloaded local copy instead, which
is convenient for offline regeneration or for reproducing a specific
Unicode version.

Usage (run from the repository root):
    # Download the latest CaseFolding.txt and regenerate the bundled
    # Swift table in its default location.
    python scripts/generate_fold_table.py

    # Use a local file instead of downloading.
    python scripts/generate_fold_table.py --input path/to/CaseFolding.txt

    # Write the table somewhere other than the default location.
    python scripts/generate_fold_table.py path/to/output.swift

The generated file is committed; the script is only re-run when bumping
the bundled Unicode version. The source CaseFolding.txt version and date
are recorded in the header comment of the generated file so that the
bundled Unicode version can be inspected without re-running the script.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
import urllib.request
from datetime import date

UNICODE_LATEST_URL = (
    "https://www.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt"
)

DEFAULT_SWIFT_OUT = os.path.join(
    "Sources", "FMUnicode", "UnicodeFoldTable.swift"
)


def parse_text(text: str) -> tuple[list[tuple[int, int]], str]:
    """Parse CaseFolding.txt content and return ((source, folded) pairs, label).

    The returned label combines the file's `# CaseFolding-X.Y.Z.txt` line
    and `# Date: ...` line so the regenerated Swift file can record exactly
    which upstream snapshot it was built from.
    """

    pairs: list[tuple[int, int]] = []
    version: str | None = None
    file_date: str | None = None

    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            body = stripped.lstrip("# ").strip()
            if version is None and body.startswith("CaseFolding-"):
                version = body
            elif file_date is None and body.lower().startswith("date:"):
                file_date = body[len("date:"):].strip()
            continue

        payload, _, _ = stripped.partition("#")
        cells = [c.strip() for c in payload.split(";")]
        if len(cells) < 4:
            continue

        code_str, status, mapping_str = cells[0], cells[1], cells[2]
        if status not in ("C", "S"):
            continue

        mapping_cells = mapping_str.split()
        if len(mapping_cells) != 1:
            # C and S are always 1:1; defensively skip anything else.
            continue

        source_cp = int(code_str, 16)
        target_cp = int(mapping_cells[0], 16)
        if source_cp != target_cp:
            pairs.append((source_cp, target_cp))

    pairs.sort()

    label = version or "unknown CaseFolding.txt"
    if file_date:
        label = "{0} (Date: {1})".format(label, file_date)
    return pairs, label


def parse_file(path: str) -> tuple[list[tuple[int, int]], str]:
    with open(path, encoding="utf-8") as f:
        return parse_text(f.read())


def download_and_parse(url: str) -> tuple[list[tuple[int, int]], str]:
    """Download CaseFolding.txt from `url` into a temp file, parse, then delete it."""

    fd, tmp_path = tempfile.mkstemp(prefix="CaseFolding-", suffix=".txt")
    os.close(fd)
    try:
        sys.stderr.write("Downloading {0}\n".format(url))
        urllib.request.urlretrieve(url, tmp_path)
        return parse_file(tmp_path)
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


SWIFT_TEMPLATE = """\
//
//  UnicodeFoldTable.swift
//
//  GENERATED FILE — DO NOT EDIT BY HAND.
//  Generated by scripts/generate_fold_table.py on {today}.
//  Source: {source_label}
//

#if EnableUnicodeReplacement

struct UnicodeFoldPair {{
    let source: UInt32
    let folded: UInt32

    init(_ source: UInt32, _ folded: UInt32) {{
        self.source = source
        self.folded = folded
    }}
}}

let unicodeFoldTable: [UnicodeFoldPair] = [
{entries}
]

#endif
"""


def emit(pairs: list[tuple[int, int]], source_label: str) -> str:
    today = date.today().isoformat()
    body_pairs = [p for p in pairs if p[0] >= 0x80]

    rows: list[str] = []
    for index in range(0, len(body_pairs), 4):
        chunk = body_pairs[index : index + 4]
        rendered = ", ".join(
            ".init(0x{src:06X}, 0x{dst:06X})".format(src=src, dst=dst)
            for src, dst in chunk
        )
        rows.append("    " + rendered + ",")

    entries = "\n".join(rows)
    return SWIFT_TEMPLATE.format(
        source_label=source_label, today=today, entries=entries
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the SwiftFMDB Unicode simple case-fold table from "
            "CaseFolding.txt. By default downloads the latest version "
            "from unicode.org into a temporary file."
        )
    )
    parser.add_argument(
        "--input",
        help=(
            "Path to a local CaseFolding.txt. If omitted, the script "
            "downloads the latest version from {0} into a temporary file "
            "that is removed once parsing completes.".format(UNICODE_LATEST_URL)
        ),
    )
    parser.add_argument(
        "swift_out",
        nargs="?",
        default=DEFAULT_SWIFT_OUT,
        help=(
            "Path to the Swift output file. Defaults to %(default)s "
            "(relative to the current working directory, which is "
            "expected to be the repository root)."
        ),
    )
    args = parser.parse_args()

    if args.input:
        pairs, source_label = parse_file(args.input)
    else:
        pairs, source_label = download_and_parse(UNICODE_LATEST_URL)

    if not pairs:
        sys.stderr.write("No fold entries parsed; refusing to overwrite output.\n")
        return 1

    swift_text = emit(pairs, source_label)

    os.makedirs(os.path.dirname(os.path.abspath(args.swift_out)) or ".", exist_ok=True)

    with open(args.swift_out, "w", encoding="utf-8", newline="\n") as f:
        f.write(swift_text)

    sys.stderr.write(
        "Wrote {0} entries from {1} to {2}.\n".format(
            len(pairs), source_label, args.swift_out
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
